site_name: Weekly benchmark
extra_css: 
   - extra.css

theme: 
  name: material
  custom_dir: overrides
   
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    

  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs  
    - content.tabs.link
    
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://bechtleperings.github.io/weekly_benchmark/

nav: 
    - "Home": "index.html"
     
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
