name: Clean Up Old Folders

on:
  push:
    branches:
      - Results

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List and cleanup folders with timestamps
        run: |
          ls -d [0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]*/ | sort -r | tail -n +11 | xargs rm -rf
