name: MkDocs Deploy

on:
  push:
    branches:
      - Results
      - origin/Results
      - master
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: define git email
        run: git config --global user.email "julian.perings@bechtle.com"

      - name: define git name
        run: git config --global user.name "bechtleperings"
        
      - name: Pull Results branch
        run: |
          cd docs && \
          git pull origin Results
          pwd
          ls

      - name: check directories
        run: |
          ls
          cd docs
          pwd
          ls

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-rtd-dropdown mkdocs-git-revision-date-plugin mkdocs-git-revision-date-localized-plugin mkdocs-yamp mkdocs-markdownextradata-plugin Pygments
      
      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force
