name: MkDocs Deploy

on:
  push:
    branches:
      - master
      - Results

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move into docs folder
        run: cd docs

      - name: Delete files and subfolders in docs folder
        run: rm -rf ./*
        
      - name: create new repo
        run: git remote add origin git@github.com:bechtleperings/weekly_benchmark.git
        
      - name: fetch repo
        run: git fetch origin

      - name: checkout Results branch
        run: git checkout -b Results origin/Results
        
      - name: Pull Results branch
        run: git pull origin Results

      - name: Move back to original directory
        run: cd ..

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-rtd-dropdown mkdocs-git-revision-date-plugin mkdocs-git-revision-date-localized-plugin mkdocs-yamp mkdocs-markdownextradata-plugin Pygments
      
      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force
